version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8502:8502"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - APP_PASSWORD=${APP_PASSWORD}
    volumes:
      - .:/app
